baseurl = "https://futurepixels.co.uk/"
theme = "futurepixels"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishDir = "docs"
author = "Nigel Greenway"
title = "Futurepixels"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
posts = "posts/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Articles on general development and programming along with other findings..."
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
jobTitle = "Lead Software Engineer"
placeOfWork = "drivvn"
lang = "en"
github = "NigelGreenway"
gitlab = "NigelGreenway"
email = "github@futurepixels.co.uk"
linkedin = "nigel-greenway-a5710a45"
photography_site = "https://500px.com/p/nigelgreenway"
primaryOS_href = "https://getsol.us/"
primaryOS_name = "Solus"

[markup.goldmark.renderer]
unsafe= true
